In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/in.csv")

In [3]:
df.city

0           Delhi
1          Mumbai
2         Kolkāta
3       Bangalore
4         Chennai
          ...    
182        Panaji
183         Damān
184     Kavaratti
185     Panchkula
186    Kagaznāgār
Name: city, Length: 187, dtype: object

In [4]:
np.array(df.city)

array(['Delhi', 'Mumbai', 'Kolkāta', 'Bangalore', 'Chennai', 'Hyderābād',
       'Pune', 'Ahmadābād', 'Sūrat', 'Lucknow', 'Jaipur', 'Cawnpore',
       'Mirzāpur', 'Nāgpur', 'Ghāziābād', 'Indore', 'Vadodara',
       'Vishākhapatnam', 'Bhopāl', 'Chinchvad', 'Patna', 'Ludhiāna',
       'Āgra', 'Kalyān', 'Madurai', 'Jamshedpur', 'Nāsik', 'Farīdābād',
       'Aurangābād', 'Rājkot', 'Meerut', 'Jabalpur', 'Thāne', 'Dhanbād',
       'Allahābād', 'Vārānasi', 'Srīnagar', 'Amritsar', 'Alīgarh',
       'Bhiwandi', 'Gwalior', 'Bhilai', 'Hāora', 'Rānchi', 'Bezwāda',
       'Chandīgarh', 'Mysore', 'Raipur', 'Kota', 'Bareilly', 'Jodhpur',
       'Coimbatore', 'Dispur', 'Guwāhāti', 'Solāpur', 'Trichinopoly',
       'Hubli', 'Jalandhar', 'Bhubaneshwar', 'Bhayandar', 'Morādābād',
       'Kolhāpur', 'Thiruvananthapuram', 'Sahāranpur', 'Warangal',
       'Salem', 'Mālegaon', 'Kochi', 'Gorakhpur', 'Shimoga', 'Tiruppūr',
       'Guntūr', 'Raurkela', 'Mangalore', 'Nānded', 'Cuttack', 'Chānda',
       'Dehra D

In [6]:
np.save("../data/cities", np.array(df.city))

In [19]:
import sys
sys.path.append('../')

In [85]:
import numpy as np

In [86]:
res_list = ['Oxygen Cylinder', 'Plasma', 'Remdesivir', 'Hospital beds', 'Oximeter', 'Ventilator']

In [87]:
np.save('../data/res.npy', res_list)

In [88]:
res = np.load('../data/res.npy', allow_pickle=True)

In [89]:
res = list(res)

In [90]:
print(res)

['Oxygen Cylinder', 'Plasma', 'Remdesivir', 'Hospital beds', 'Oximeter', 'Ventilator']


In [14]:
dictn = dict(zip(res, [0]*len(res)))

In [15]:
dictn

{'Verified Oxygen Cylinder': 0,
 'Plasma': 0,
 'Remdisvir': 0,
 'Hospital beds': 0,
 'Oximeter': 0,
 'Ventilator': 0}

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 7, 8, 2, 0.1, 3, 15, 2.5])
print("Original arrays:")
print(array1)

Original arrays:
[ 1.   7.   8.   2.   0.1  3.  15.   2.5]


In [3]:
k = 4
result = np.argpartition(array1, k)
print("\nk smallest values:")
print(array1[result[:k]])


k smallest values:
[0.1 1.  2.  2.5]


In [6]:
array1[result[:k]]

array([0.1, 1. , 2. , 2.5])

In [3]:
dict(np.load('data/de'fault_dict.npy', allow_pickle= True))

FileNotFoundError: [Errno 2] No such file or directory: 'data/default_dict.npy'

In [1]:
import json

In [3]:
f = open('../telegram_request.json')

In [4]:
data = json.load(f)

In [5]:
data

{'update_id': 900070988,
 'message': {'message_id': 61,
  'from': {'id': 1721282209,
   'is_bot': False,
   'first_name': 'Nidhir',
   'last_name': 'Bhavsar',
   'language_code': 'en'},
  'chat': {'id': 1721282209,
   'first_name': 'Nidhir',
   'last_name': 'Bhavsar',
   'type': 'private'},
  'date': 1619879684,
  'text': 'nidhir bhavsar\nnid989@gmail.com\n8160790964\nvadodara\ngujarat\n1 2 5\ndescription',
  'entities': [{'offset': 15, 'length': 16, 'type': 'email'},
   {'offset': 32, 'length': 10, 'type': 'phone_number'}]}}

In [8]:
data["message"]["chat"]["id"]

1721282209

In [77]:
dl = ['nidhir', '8160790964', 'nid989@nid.com', 'Vadodara', 'Gujarat', ['Remdisvir', 'Hospital beds', 'Ventilator'], '']

In [78]:
dl

['nidhir',
 '8160790964',
 'nid989@nid.com',
 'Vadodara',
 'Gujarat',
 ['Remdisvir', 'Hospital beds', 'Ventilator'],
 '']

In [3]:
ci = 1721282209
ci

1721282209

In [4]:
def save_details(detail_list, chat_id):
    detail_list.append(cdhat_id)
    np.save("detail_list", detail_list)

In [7]:
import numpy as np

In [6]:
dict_ = {'Name': '', 'Mobile': '', 'Email': '', 'City': '', 'State': '', 'Resources': [''], 'Description': ''} 

In [80]:
dict_['chat_id'] = ''
dict_['has_plasma'] = False

In [7]:
dict_

{'Name': '',
 'Mobile': '',
 'Email': '',
 'City': '',
 'State': '',
 'Resources': [''],
 'Description': ''}

In [8]:
np.save('../data/default_dict', dict_)

In [9]:
x = np.load('../data/default_dict.npy', allow_pickle=True)

In [10]:
x

array({'Name': '', 'Mobile': '', 'Email': '', 'City': '', 'State': '', 'Resources': [''], 'Description': ''},
      dtype=object)

In [22]:
a = dict(enumerate(x.flatten(), 1))
print()a

{1: {'Name': 'nidhir Bhavsar', 'Mobile': '8160790964', 'Email': 'nidbhavsar989@gmail.com', 'City': 'Vadodara', 'State': 'Gujarat', 'Resources': ['Hospital beds', 'Oximeter'], 'Description': '', 'chat_id': 1721282209, 'has_plasma': True}}


In [18]:
a[1]["chat_id"]

1721282209

In [64]:
import json
f = open('../telegram_request.json')
user_data = json.load(f)
txt = user_data["message"]["text"]

In [91]:
print(txt)

nidhir
nidbhavsar989@gmail.com
8160790964
Vakodara
Gujarat
2 3 4
description


In [99]:
x = repr(txt)
x

"'nidhir\\nnidbhavsar989@gmail.com\\n8160790964\\nVakodara\\nGujarat\\n2 3 4\\ndescription'"

In [104]:
a = txt.replace("\n", "\\n")
a

'nidhir\\nnidbhavsar989@gmail.com\\n8160790964\\nVakodara\\nGujarat\\n2 3 4\\ndescription'

In [105]:
# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"^([a-zA-Z]+(\\n[a-zA-Z]+)+)([0-9]*)@[a-zA-Z]+\.([a-zA-Z]+(\\[a-zA-Z]+)+)[0-9]+\\n([a-zA-Z]+(\\n[a-zA-Z]+)+)\\n([0-9]+( [0-9]+)*)\\n[a-zA-Z].*$"



test_str = "nidhir\\nnidbhavsar989@gmail.com\\n8160790964\\nVakodara\\nGujarat\\n2 3 4\\ndescription"

print(test_str)
print(type(test_str))

matches = re.match(regex, a)

# if matches:
#     print ("Match was found at {start}-{end}: {match}".format(start = matches.start(), end = matches.end(), match = matches.group()))
    
#     for groupNum in range(0, len(matches.groups())):
#         groupNum = groupNum + 1
        
#         print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = matches.start(groupNum), end = matches.end(groupNum), group = matches.group(groupNum)))

# # Note: for Python 2.7 compatibility, use ur"" to prefix the regex and u"" to prefix the test string and substitution.
if matches:
    print("yes")
else:
    print("no")

nidhir\nnidbhavsar989@gmail.com\n8160790964\nVakodara\nGujarat\n2 3 4\ndescription
<class 'str'>
yes


In [107]:
regex = r"^[0-9]\sin\s[a-zA-Z]+$"

test_str = "2 in vadoara"

matches = re.match(regex, test_str)

# if matches:
#     print ("Match was found at {start}-{end}: {match}".format(start = matches.start(), end = matches.end(), match = matches.group()))
    
#     for groupNum in range(0, len(matches.groups())):
#         groupNum = groupNum + 1
        
#         print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = matches.start(groupNum), end = matches.end(groupNum), group = matches.group(groupNum)))
if matches:
    print("yes")
else:
    print("no")

yes


In [113]:
def example():
    a = "nidhir\\nnidbhavsar989@gmail.com\\n8160790964\\nVakodara\\nGujarat\\n2 3 4\\ndescription"
    regex = r"^([a-zA-Z]+(\\n[a-zA-Z]+)+)([0-9]*)@[a-zA-Z]+\.([a-zA-Z]+(\\[a-zA-Z]+)+)[0-9]+\\n([a-zA-Z]+(\\n[a-zA-Z]+)+)\\n([0-9]+( [0-9]+)*)\\n[a-zA-Z].*$"
    matches = re.match(regex, a)

    if matches:
        return "true"
    else: 
        regex = r"^[0-9]\sin\s[a-zA-Z]+$"
        matches = re.match(regex, a)
        if matches:
            return "true 2"
        else:
            regex = r"^[a-zA-Z]{1,2}(\+|\-)+( [a-zA-Z]{1,2}(\+|\-))*.*$"
            matches = re.match(regex, a)
            if matches:
                return "true"
            else:
                pass
    return "none"

In [117]:
txt = "1\ in vadodara"
a = txt.replace('\n','\\n')
a

'1 in vadodara'

In [6]:
# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"^[a-zA-Z]{1,2}(\+|\-)+( [a-zA-Z]{1,2}(\+|\-))*.*$"

test_str = "AB+ AB-"

matches = re.finditer(regex, test_str, re.DOTALL)

for matchNum, match in enumerate(matches, start=1):
    
    print ("Match {matchNum} was found at {start}-{end}: {match}".format(matchNum = matchNum, start = match.start(), end = match.end(), match = match.group()))
    
    for groupNum in range(0, len(match.groups())):
        groupNum = groupNum + 1
        
        print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = match.start(groupNum), end = match.end(groupNum), group = match.group(groupNum)))

# Note: for Python 2.7 compatibility, use ur"" to prefix the regex and u"" to prefix the test string and substitution.


Match 1 was found at 0-7: AB+ AB-
Group 1 found at 2-3: +
Group 2 found at 3-7:  AB-
Group 3 found at 6-7: -


In [6]:
x = "1 in Vadodara"
s = x.split("in")
print(s)
print([i.strip() for i in s])

['1 ', ' Vadodara']
['1', 'Vadodara']


In [51]:
x =[['Aakash', 'Mumbai', 'Maharashtra', '7859860581', 'Plasma,Remdisvir,Hospital beds,Plasma_ab+ve,Plasma_ab-ve,', '', '2021-05-03T11:01:34.951Z'], ['Aakash', 'Mumbai', 'Maharashtra', '7859860581', 'Remdisvir,Hospital beds,', '', '2021-05-03T11:03:43.351Z'], ['Aakash', 'Mumbai', 'Maharashtra', '7859860581', 'Plasma,Remdisvir,Hospital beds,Plasma_ab+ve,Plasma_ab-ve,', '', '2021-05-03T11:04:08.094Z'], ['Aakash', 'Mumbai', 'Maharashtra', '7859860581', 'Remdisvir,Hospital beds,', '', '2021-05-03T11:07:45.962Z'], ['nidhir', 'Mumbai', 'Maharashtra', '8160790964', 'Remdisvir,Hospital beds,', '', '2021-05-03T11:07:45.962Z'], ['khimendra', 'Mumbai', 'Maharashtra', '9016667385', 'Remdisvir,Hospital beds,', '', '2021-05-03T11:07:45.962Z'],['Khimendra', 'Mumbai', 'Maharashtra', '9016667385', 'Remdisvir,Hospital beds,', '', '2021-05-03T11:07:45.962Z']]

In [52]:
list_ = []
for i in x:
    name = i[0].lower()
    mobile = i[3] 
    temp = [name, mobile]
    list_.append(temp)
print(list_)

[['aakash', '7859860581'], ['aakash', '7859860581'], ['aakash', '7859860581'], ['aakash', '7859860581'], ['nidhir', '8160790964'], ['khimendra', '9016667385'], ['khimendra', '9016667385']]


In [58]:
res = list(set(map(lambda i: tuple(sorted(i)), list_)))

aakash 7859860581
nidhir 8160790964
khimendra 9016667385


In [53]:
for i in res:
    print(i[1], i[0])

In [63]:
temp_msg = ""
for i in res:
    temp_msg = temp_msg + "{0:<5} {1}".format(i[1], i[0]) + "\n"

In [64]:
print(temp_msg)

aakash 7859860581
nidhir 8160790964
khimendra 9016667385



In [1]:
states = ["Andhrapradesh","Arunachalpradesh ","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","JammuandKashmir","Jharkhand","Karnataka","Kerala","Madhypradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamilnadu","Telangana","Tripura","Uttarpradesh","Uttarakhand","West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli","Daman and Diu","Lakshadweep","Delhi","Puducherry"]

In [2]:
import numpy as np
np.load('../data/states.npy')

array(['Andhra Pradesh', 'Arunachal Pradesh ', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands',
       'Chandigarh', 'Dadra and Nagar Haveli', 'Daman and Diu',
       'Lakshadweep', 'Delhi', 'Puducherry'], dtype='<U27')

In [3]:
np.save('../data/states.npy', states)

In [5]:
a = 2
if a == 2:
    pass
else:
    print("nidhir")