In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/in.csv")

In [3]:
df.city

0           Delhi
1          Mumbai
2         Kolkāta
3       Bangalore
4         Chennai
          ...    
182        Panaji
183         Damān
184     Kavaratti
185     Panchkula
186    Kagaznāgār
Name: city, Length: 187, dtype: object

In [4]:
np.array(df.city)

array(['Delhi', 'Mumbai', 'Kolkāta', 'Bangalore', 'Chennai', 'Hyderābād',
       'Pune', 'Ahmadābād', 'Sūrat', 'Lucknow', 'Jaipur', 'Cawnpore',
       'Mirzāpur', 'Nāgpur', 'Ghāziābād', 'Indore', 'Vadodara',
       'Vishākhapatnam', 'Bhopāl', 'Chinchvad', 'Patna', 'Ludhiāna',
       'Āgra', 'Kalyān', 'Madurai', 'Jamshedpur', 'Nāsik', 'Farīdābād',
       'Aurangābād', 'Rājkot', 'Meerut', 'Jabalpur', 'Thāne', 'Dhanbād',
       'Allahābād', 'Vārānasi', 'Srīnagar', 'Amritsar', 'Alīgarh',
       'Bhiwandi', 'Gwalior', 'Bhilai', 'Hāora', 'Rānchi', 'Bezwāda',
       'Chandīgarh', 'Mysore', 'Raipur', 'Kota', 'Bareilly', 'Jodhpur',
       'Coimbatore', 'Dispur', 'Guwāhāti', 'Solāpur', 'Trichinopoly',
       'Hubli', 'Jalandhar', 'Bhubaneshwar', 'Bhayandar', 'Morādābād',
       'Kolhāpur', 'Thiruvananthapuram', 'Sahāranpur', 'Warangal',
       'Salem', 'Mālegaon', 'Kochi', 'Gorakhpur', 'Shimoga', 'Tiruppūr',
       'Guntūr', 'Raurkela', 'Mangalore', 'Nānded', 'Cuttack', 'Chānda',
       'Dehra D

In [6]:
np.save("../data/cities", np.array(df.city))

In [19]:
import sys
sys.path.append('../')

In [20]:
import utility

In [40]:
res_list = ['Verified Oxygen Cylinder', 'Plasma', 'Remdisvir', 'Hospital beds', 'Oximeter', 'Ventilator']

In [41]:
np.save('data/res.npy', res_list)

In [11]:
res = np.load('data/res.npy', allow_pickle=True)

In [12]:
res = list(res)

In [13]:
print(res)

['Verified Oxygen Cylinder', 'Plasma', 'Remdisvir', 'Hospital beds', 'Oximeter', 'Ventilator']


In [14]:
dictn = dict(zip(res, [0]*len(res)))

In [15]:
dictn

{'Verified Oxygen Cylinder': 0,
 'Plasma': 0,
 'Remdisvir': 0,
 'Hospital beds': 0,
 'Oximeter': 0,
 'Ventilator': 0}

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 7, 8, 2, 0.1, 3, 15, 2.5])
print("Original arrays:")
print(array1)

Original arrays:
[ 1.   7.   8.   2.   0.1  3.  15.   2.5]


In [3]:
k = 4
result = np.argpartition(array1, k)
print("\nk smallest values:")
print(array1[result[:k]])


k smallest values:
[0.1 1.  2.  2.5]


In [6]:
array1[result[:k]]

array([0.1, 1. , 2. , 2.5])

In [3]:
dict(np.load('data/de'fault_dict.npy', allow_pickle= True))

FileNotFoundError: [Errno 2] No such file or directory: 'data/default_dict.npy'

In [1]:
import json

In [3]:
f = open('../telegram_request.json')

In [4]:
data = json.load(f)

In [5]:
data

{'update_id': 900070988,
 'message': {'message_id': 61,
  'from': {'id': 1721282209,
   'is_bot': False,
   'first_name': 'Nidhir',
   'last_name': 'Bhavsar',
   'language_code': 'en'},
  'chat': {'id': 1721282209,
   'first_name': 'Nidhir',
   'last_name': 'Bhavsar',
   'type': 'private'},
  'date': 1619879684,
  'text': 'nidhir bhavsar\nnid989@gmail.com\n8160790964\nvadodara\ngujarat\n1 2 5\ndescription',
  'entities': [{'offset': 15, 'length': 16, 'type': 'email'},
   {'offset': 32, 'length': 10, 'type': 'phone_number'}]}}

In [8]:
data["message"]["chat"]["id"]

1721282209

In [26]:
dl = ['nidhir', '8160790964', 'nid989@nid.com', 'Vadodara', 'Gujarat', ['Remdisvir', 'Hospital beds', 'Ventilator'], '']

In [27]:
dl

['nidhir',
 '8160790964',
 'nid989@nid.com',
 'Vadodara',
 'Gujarat',
 ['Remdisvir', 'Hospital beds', 'Ventilator'],
 '']

In [3]:
ci = 1721282209
ci

1721282209

In [4]:
def save_details(detail_list, chat_id):
    detail_list.append(cdhat_id)
    np.save("detail_list", detail_list)

In [2]:
import numpy as np

In [2]:
dict_ = {'Name': 'nidhir', 'Mobile': '8160790964', 'Email': 'nid989@nid.com', 'City': 'Vadodara', 'State': 'Gujarat', 'Resources': ['Remdisvir', 'Hospital beds', 'Ventilator'], 'Description': ''} 

In [7]:
dict_['chat_id'] = '1721282209'

In [8]:
dict_

{'Name': 'nidhir',
 'Mobile': '8160790964',
 'Email': 'nid989@nid.com',
 'City': 'Vadodara',
 'State': 'Gujarat',
 'Resources': ['Remdisvir', 'Hospital beds', 'Ventilator'],
 'Description': '',
 'chat_id': '1721282209'}

In [11]:
np.save('../data/beta_dict', dict_)

In [3]:
np.load('../data/beta_dict.npy', allow_pickle=True)

array({'Name': 'nidhir bhavsar', 'Mobile': '9016667385', 'Email': 'bhavsarmanan@gmail.com', 'City': 'Vadodara', 'State': 'Gujarat', 'Resources': ['Remdisvir', 'Hospital beds', 'Oximeter'], 'Description': '', 'chat_id': 1721282209},
      dtype=object)